### ISSUE TITLE
Mobile Navbar issue

### ISSUE THREAD

**Issue by galabra** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#23]
Hi there,
I'm currently setting my app's mobile version, while the desktop version works beautifully.
When I switch to mobile view, the navbar that I set on top of the app shows completely empty.
In addition, the navbar isn't `fixed` to the top of the screen, even though I added the `fixedTop` property.

I believe it's a similar case to [this one](https://stackoverflow.com/questions/36855473/position-fixed-not-working-is-working-like-absolute/36857029).

How can I solve it?
Thank you.

**Comment by einazare** [comment]
Hello there @galabra ,

To make the navbar fixed to top, you need to navigate inside `src/components/Header/Header.jsx` and change `<Navbar fluid>` to `<Navbar fluid className="navbar-fixed">`.
The other thing, i am not sure why you have the navbar empty, can you please provide me with some steps on how to recreate the problem? Also, some screenshots would be awesome, since our product looks grate on mobile too:
![screen shot 2018-09-10 at 12 12 26 pm](https://user-images.githubusercontent.com/26245512/45288312-08a6c580-b4f3-11e8-97ff-f6a85217dd92.png)
![41437015_2056305628013291_5422690635503108096_n](https://user-images.githubusercontent.com/26245512/45288323-0f353d00-b4f3-11e8-9c9d-4470f68872c1.jpg)



Best,
Manu

**Comment by galabra** [comment]
Hi @EINazare ,
Thanks a lot for the quick reply!

I tried adding the `className="navbar-fixed"` but it still occurs empty and not fixed.

The following is my React code:
```
<Navbar fluid className="navbar-fixed">
    <Navbar.Collapse>
        <Nav>
            <NavItem>
                <Link to={"/dashboard?industryId=" + this.props.currentIndustry.industryId}>DASHBOARD</Link>
            </NavItem>
        </Nav>
    </Navbar.Collapse>
</Navbar>
```

And this is how it renders:
<img width="884" alt="screen shot 2018-09-10 at 13 03 43" src="https://user-images.githubusercontent.com/20545256/45291314-7c000580-b4fa-11e8-9fd6-de8e9a33a577.png">

However, as I mentioned, I can't see the `NavItem` and the menu isn't fixed.

Thanks again for your quick reply,
looking forward to your assistance,
Gal

**Comment by einazare** [comment]
Hello again @galabra ,

As per my other comment, you should use `navbar-fixed`, also, we have covered this in our live docs here: [https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/navigation](https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/documentation/navigation).
The `navbar-fixed-top` class from bootstrap 3 will create a horizontal scroll (check it out - you should have a horizontal scroll). 
The fact that your navbar is blank i do not think is because of the `navbar-fixed` or `navbar-fixed-top` classes. I think is because you have a new route which you do not set it dynamically probably.
If you navigate inside `src/components/Header/Header.jsx` you will see at line 67 (also please see lines 18-42) that we create the navbar brand dynamically based on our routes from `src/routes/dashboard.jsx`.
![screen shot 2018-09-10 at 5 32 16 pm 2](https://user-images.githubusercontent.com/26245512/45304308-7ddcbf80-b520-11e8-8d65-904488b5f633.png)


Hope this info helps you.

Best,
Manu

**Comment by galabra** [comment]
Hi @EINazare ,
The classes are indeed added to the navbar rendered element, as written in the Bootstrap documentation.
However I get the result I've described in the original post: an empty and non-fixed bar.
<img width="1276" alt="screen shot 2018-09-10 at 18 11 57" src="https://user-images.githubusercontent.com/20545256/45306339-183f0200-b525-11e8-8971-b447a80e30d0.png">

**Comment by galabra** [comment]
The solution to fixing the navbar to the top of the page was removing the `@include transform-translate-x(0px);` from the CSS properties of the navbar's parent element.

In short, I've removed `@include transform-translate-x(0px);` from the properties of `.main-panel,
    .wrapper-full-page` inside `_responsive.scss`.

The idea came after reading these answers:
https://stackoverflow.com/a/28512658/3103891
https://stackoverflow.com/a/18529444/3103891

Now I still need to figure why's the navbar empty.
Maybe this will help: when I examine navbar's child element in Chrome Developer Tools - its height is 0.

**Comment by galabra** [comment]
So the final answer I was looking for is:

> A `<Navbar>` element **must** include a <Navbar.Header>, otherwise it will show empty.

Additionally, the header must include `<Navbar.Toggle />` in order to present the hamburger button, that opens the menu.

Thanks for the help!

**Comment by einazare** [comment]
Hello again @galabra ,

Why do you have the class `navbar-static-top` onto your navbar?
You should not have that.
Also, maybe the navbar is empty since you do not make the brand?
Change line 67 from `src/components/Header/Header.jsx` from `<a href="#pablo">{this.makeBrand()}</a>` to `<a href="#pablo">Hello from navbar brand</a>` and see if this works.

Best,
Manu
