### ISSUE TITLE
Question: what general store would you recommend?

### ISSUE THREAD

**Issue by Mulli** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#25]
Seems to me that in my case I shall have to use general store (Redux or similar)
What is your recommendation?
Is there any internal support for such need?
Thanks

**Comment by einazare** [comment]
Hello there @Mulli ,

At the moment none of our React products make use of Redux, and we only offer support for issues with our product, not with the development of it.
I've followed [this tutorial ](https://medium.com/backticks-tildes/setting-up-a-redux-project-with-create-react-app-e363ab2329b8)a few days ago about Redux, and from what I can see, adding Redux on our templates is quite easy. You just need to install redux and react-redux and you're good to go.
After that, you can use Redux however you want it. And this is why we can't offer support for Redux, because from one app to another, the functions are different, and we can't do them all, the possibilities for this functions are infinite. I hope you can understand this.

Best,
Manu
