### ISSUE TITLE
server side data for datatable

### ISSUE THREAD

**Issue by cesoftinfo** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#3]
Any hint for server side datatable rendering?

**Comment by einazare** [comment]
Hello @cesoftinfo and thank you for your interest in our products. 

I am not sure about what your question is. You want to populate the datatable from a database? 
If this is the case, the best way is to use ajax. Make an ajax call to your server/database and after that is just as we've done in our demo. 
We have dataRows ( see line 17 and 20 in `src/views/Tables/DataTables.jsx`) and with this we populate the body of the table (see lines 139-160 in `src/views/Tables/DataTables.jsx`). 
You can do the same with an ajax call and save the result in a variable. I would make this call in the constructor of my component or in the `componentWillMount()` function so that the ajax call would be done before the render function. After that in the render function i would map that variable to create the body of the table like in `src/views/Tables/DataTables.jsx`, lines 139-160.

I hope this information helps you and if we can help you with anything else, please let us know.

All the best, 
Manu
