### ISSUE TITLE
How to rewrite CSS in Ractable 

### ISSUE THREAD

**Issue by thanhtungka91** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#32]
i want to overwirte css of reactable. 
in this case 
.ReactTable .rt-table {
     overflow: hidden; 
}
i want to change `overflow` to `auto`.

<img width="1306" alt="screen shot 2019-02-11 at 15 36 49" src="https://user-images.githubusercontent.com/3795067/52548790-f965d400-2e12-11e9-9e32-899907c033e6.png">

**Comment by einazare** [comment]
Hello again, @thanhtungka91 ,

Since we do not recommend changing our own styles, you can create your own css file, and then import it inside index.js after our own css files.
In that file you just write:
```
.ReactTable .rt-table {
    overflow: auto;
}
```
And it should override our style.

Hope this information was of help. Let me know if everything works fine.

Best,
Manu
